version: '3.8'
services:
  # ZOOKEEPER
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: demo-zookeeper
    restart: unless-stopped
    ports:
      - 2181:2181
    environment:
      JVMFLAGS: "-Xmx256M -Xms128M"
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOO_AUTOPURGE_SNAPRETAINCOUNT: 10
      ZOO_AUTOPURGE_PURGEINTERVAL: 2
    volumes:
      - "./.volumes/zookeeper/data:/var/lib/zookeeper/data"
      - "./.volumes/zookeeper/lib-log:/var/lib/zookeeper/log"
      - "./.volumes/zookeeper/log:/var/log/zookeeper"
    healthcheck:
      test: "nc -w 5 -z localhost 2181 || exit -1"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 120s
  # KAFKA
  kafka:
    image: confluentinc/cp-enterprise-kafka:latest
    container_name: demo-kafka
    restart: unless-stopped
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - 9092:29092
    environment:
      KAFKA_HEAP_OPTS: '-Xmx256M -Xms128M'
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - "./.volumes/kafka/data:/var/lib/kafka/data"
      - "./.volumes/kafka/log:/var/log/kafka"
    healthcheck:
      test: "nc -w 5 -z localhost 9092 || exit -1"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 120s
  # KAFKA UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: demo-kafka-ui
    ports:
      - 8080:8080
    depends_on:
      - zookeeper
      - kafka
      # - kafka-connect
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schemaregistry:8085
      # KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: first
      # KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect0:8083